// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKt5QFBIDL_sUJ1Oq5am0Rxvn5VlTnEpE',
    appId: '1:420113511598:web:d0059cf3a9eb833422293f',
    messagingSenderId: '420113511598',
    projectId: 'gfacil-599a4',
    authDomain: 'gfacil-599a4.firebaseapp.com',
    storageBucket: 'gfacil-599a4.appspot.com',
    measurementId: 'G-4GD0X1MZ8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkQe6C3hWbXrQEW5poyp0v5LJqh4SLBlQ',
    appId: '1:420113511598:android:aea449361a0bd69b22293f',
    messagingSenderId: '420113511598',
    projectId: 'gfacil-599a4',
    storageBucket: 'gfacil-599a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSJQLXotKvlSiaCd9lGo8hR-zcu5m87XM',
    appId: '1:420113511598:ios:31da31eebd8236c822293f',
    messagingSenderId: '420113511598',
    projectId: 'gfacil-599a4',
    storageBucket: 'gfacil-599a4.appspot.com',
    iosBundleId: 'com.example.definitivoAppTcc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSJQLXotKvlSiaCd9lGo8hR-zcu5m87XM',
    appId: '1:420113511598:ios:88f7339c6cd4e62322293f',
    messagingSenderId: '420113511598',
    projectId: 'gfacil-599a4',
    storageBucket: 'gfacil-599a4.appspot.com',
    iosBundleId: 'com.example.definitivoAppTcc.RunnerTests',
  );
}
